### ISSUE TITLE
is it support yolov5-node?

### ISSUE THREAD

**Issue by winktool** [Hyuto/yolov7-node#1] opened 2022-11-22 12:44 UTC

**Comment by winktool** [comment] 2022-11-22 15:12
I am new to this field and look forward to your release of the new version about yolov5.

**Comment by Hyuto** [comment] 2022-11-24 06:50
Sorry but I'm not going to create new repo for this but you could use this project folder as I said before. Mostly YOLOv5 and YOLOv7 work the same way when we deploy it on `onnxruntime`, but the problem is YOLOv5 exported onnx model doesn't have NMS layer on it so we have to implement this manually (the performance is really bad compared to NMS on the model, but it works 😆) .

1. Add YOLOv5 `onnx` model to the project. Move it to `src` folder
2. Change model and model configuration in `src/index.js`
   ```js
   ...
   // model configs
   const modelInfo = {
       name: "yolov5n.onnx",
       inputShape: [1, 3, 640, 640],
   };
   const confidenceThreshold = 0.25;
   const classThreshold = 0.25;
   const iouThreshold = 0.45; // overlap threshold
   ...
   ```
   Note: I use yolov5 lightest model `yolov5n` here, as for the thresholds you can tweak it yourself
3. Add NMS algorithm on `src/index.js`

   ```js
   ...
   const NMS = (boxes, overlapThresh) => {
       // source : https://github.com/Hyuto/yolov5-onnxruntime-web/blob/master/src/utils/nms.js
       if (boxes.length === 0) {
           return [];
       }

       const pick = [];

       boxes.sort((b1, b2) => {
           return b1.confidence - b2.confidence;
       });

       while (boxes.length > 0) {
           let last = boxes[boxes.length - 1];
           pick.push(last);
           let suppress = [last];

           for (let i = 0; i < boxes.length - 1; i++) {
               const box = boxes[i];
               const xx1 = Math.max(box.bounding[0], last.bounding[0]);
               const yy1 = Math.max(box.bounding[1], last.bounding[1]);
               const xx2 = Math.min(box.bounding[0] + box.bounding[2], last.bounding[0] + last.bounding[2]);
               const yy2 = Math.min(box.bounding[1] + box.bounding[3], last.bounding[1] + last.bounding[3]);
               const w = Math.max(0, xx2 - xx1 + 1);
               const h = Math.max(0, yy2 - yy1 + 1);
               const overlap = (w * h) / ((box.bounding[2] + 1) * (box.bounding[3] + 1));

               if (overlap > overlapThresh) {
                   suppress.push(boxes[i]);
               }
           }

           boxes = boxes.filter((box) => {
               return !suppress.find((supp) => {
                   return supp === box;
               });
           });
       }
       return pick;
   };
   ```

4. Modifying `detect` function on `src/index.js`

   ```js
   ...
   const detect = async (frame) => {
     const input = new Float32Array(frame.buffer);
     const tensor = new ort.Tensor("float32", input, modelInfo.inputShape); // to ort.Tensor
     const { output0 } = await session.run({ images: tensor }); // run session and get output layer
     const boxes = [];

     // looping through output
     for (let r = 0; r < output0.data.length; r += output0.dims[2]) {
       const data = output0.data.slice(r, r + output0.dims[2]); // get rows
       const scores = data.slice(5); // classes probability scores
       const confidence = data[4]; // detection confidence
       const classId = scores.indexOf(Math.max(...scores)); // class id of maximum probability scores
       const maxClassProb = scores[classId]; // maximum probability scores

       // filtering by thresholds
       if (confidence >= confidenceThreshold && maxClassProb >= classThreshold) {
         const [x, y, w, h] = data.slice(0, 4);
         boxes.push({
           classId: classId,
           probability: maxClassProb,
           confidence: confidence,
           bounding: [x - 0.5 * w, y - 0.5 * h, w, h],
         });
       }
     }

     // filtering boxes using Non Maximum Suppression algorithm
     const selectedBoxes = NMS(boxes, iouThreshold);
     return selectedBoxes;
   };
   ...
   ```

5. And run the project like always `yarn start`

**Comment by winktool** [comment] 2022-11-24 06:51
Thank you very much!

**Comment by Hyuto** [comment] 2022-11-26 03:43
Since there's no problem occur, I'm closing this issue.

**Closed by Hyuto** 2022-11-26 03:43 UTC
